# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_cut2.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cut(object):
    def setupUi(self, Ui_cut):
        Ui_cut.setObjectName("Ui_cut")
        Ui_cut.resize(1300, 817)
        self.centralwidget = QtWidgets.QWidget(Ui_cut)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 15, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SubList = QtWidgets.QVBoxLayout()
        self.SubList.setObjectName("SubList")
        self.MP4Title_2 = SubtitleLabel(self.centralwidget)
        self.MP4Title_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.MP4Title_2.setFont(font)
        self.MP4Title_2.setObjectName("MP4Title_2")
        self.SubList.addWidget(self.MP4Title_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.AutoMarkBtn = PushButton(self.centralwidget)
        self.AutoMarkBtn.setObjectName("AutoMarkBtn")
        self.horizontalLayout_4.addWidget(self.AutoMarkBtn)
        self.ImportRoleBtn = PushButton(self.centralwidget)
        self.ImportRoleBtn.setObjectName("ImportRoleBtn")
        self.horizontalLayout_4.addWidget(self.ImportRoleBtn)
        self.OutputRoleBtn = PushButton(self.centralwidget)
        self.OutputRoleBtn.setObjectName("OutputRoleBtn")
        self.horizontalLayout_4.addWidget(self.OutputRoleBtn)
        self.SubList.addLayout(self.horizontalLayout_4)
        self.MP4Box_2 = QtWidgets.QWidget(self.centralwidget)
        self.MP4Box_2.setMinimumSize(QtCore.QSize(0, 430))
        self.MP4Box_2.setObjectName("MP4Box_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.MP4Box_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.SubScroll = QtWidgets.QScrollArea(self.MP4Box_2)
        self.SubScroll.setStyleSheet("")
        self.SubScroll.setWidgetResizable(True)
        self.SubScroll.setObjectName("SubScroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 941, 498))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SubScroll.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.SubScroll, 0, 0, 1, 1)
        self.SubList.addWidget(self.MP4Box_2)
        self.SubList.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.SubList)
        self.Mkv = QtWidgets.QVBoxLayout()
        self.Mkv.setContentsMargins(-1, -1, -1, 0)
        self.Mkv.setSpacing(6)
        self.Mkv.setObjectName("Mkv")
        self.MkvTitle = SubtitleLabel(self.centralwidget)
        self.MkvTitle.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.MkvTitle.setFont(font)
        self.MkvTitle.setObjectName("MkvTitle")
        self.Mkv.addWidget(self.MkvTitle)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddVideoBtn = PushButton(self.centralwidget)
        self.AddVideoBtn.setObjectName("AddVideoBtn")
        self.horizontalLayout.addWidget(self.AddVideoBtn)
        self.AIVoiceBtn = PushButton(self.centralwidget)
        self.AIVoiceBtn.setObjectName("AIVoiceBtn")
        self.horizontalLayout.addWidget(self.AIVoiceBtn)
        self.CosyDubbingBtn = PushButton(self.centralwidget)
        self.CosyDubbingBtn.setObjectName("CosyDubbingBtn")
        self.horizontalLayout.addWidget(self.CosyDubbingBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(3, 4)
        self.Mkv.addLayout(self.horizontalLayout)
        self.CustomVideoLayout = QtWidgets.QWidget(self.centralwidget)
        self.CustomVideoLayout.setStyleSheet("#CustomVideoLayout{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.CustomVideoLayout.setObjectName("CustomVideoLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CustomVideoLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Mkv.addWidget(self.CustomVideoLayout)
        self.Mkv.setStretch(0, 1)
        self.Mkv.setStretch(1, 1)
        self.Mkv.setStretch(2, 100)
        self.horizontalLayout_2.addLayout(self.Mkv)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BottomFrame = QtWidgets.QFrame(self.centralwidget)
        self.BottomFrame.setStyleSheet("#BottomFrame{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.BottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomFrame.setObjectName("BottomFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.BottomFrame)
        self.verticalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.controlFrame = QtWidgets.QFrame(self.BottomFrame)
        self.controlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.controlFrame.setObjectName("controlFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.controlFrame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(1034, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.btn = PushButton(self.controlFrame)
        self.btn.setObjectName("btn")
        self.horizontalLayout_3.addWidget(self.btn)
        self.trackScaleSlider = Slider(self.controlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(27)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackScaleSlider.sizePolicy().hasHeightForWidth())
        self.trackScaleSlider.setSizePolicy(sizePolicy)
        self.trackScaleSlider.setMinimumSize(QtCore.QSize(150, 0))
        self.trackScaleSlider.setMinimum(10)
        self.trackScaleSlider.setMaximum(300)
        self.trackScaleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.trackScaleSlider.setObjectName("trackScaleSlider")
        self.horizontalLayout_3.addWidget(self.trackScaleSlider)
        self.verticalLayout_4.addWidget(self.controlFrame)
        self.line = QtWidgets.QFrame(self.BottomFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.trackFrame = QtWidgets.QFrame(self.BottomFrame)
        self.trackFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trackFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.trackFrame.setObjectName("trackFrame")
        self.verticalLayout_4.addWidget(self.trackFrame)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.BottomFrame)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.setStretch(0, 5)
        self.verticalLayout_3.setStretch(1, 2)
        Ui_cut.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ui_cut)
        QtCore.QMetaObject.connectSlotsByName(Ui_cut)

    def retranslateUi(self, Ui_cut):
        _translate = QtCore.QCoreApplication.translate
        Ui_cut.setWindowTitle(_translate("Ui_cut", "MainWindow"))
        self.MP4Title_2.setText(_translate("Ui_cut", "配音字幕列表"))
        self.AutoMarkBtn.setText(_translate("Ui_cut", "AI标注"))
        self.ImportRoleBtn.setText(_translate("Ui_cut", "导入角色表"))
        self.OutputRoleBtn.setText(_translate("Ui_cut", "导出角色表"))
        self.MkvTitle.setText(_translate("Ui_cut", "视频"))
        self.AddVideoBtn.setText(_translate("Ui_cut", "上传视频"))
        self.AIVoiceBtn.setText(_translate("Ui_cut", "AI声线转换"))
        self.CosyDubbingBtn.setText(_translate("Ui_cut", "CosyVoice配音"))
        self.btn.setText(_translate("Ui_cut", "预留"))
from qfluentwidgets import PushButton, Slider, SubtitleLabel
