# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_dubbing.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dubbing(object):
    def setupUi(self, Dubbing):
        Dubbing.setObjectName("Dubbing")
        Dubbing.resize(1300, 910)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dubbing)
        self.verticalLayout.setContentsMargins(12, 32, 16, 16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PackageTitile = QtWidgets.QLabel(Dubbing)
        self.PackageTitile.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.PackageTitile.setFont(font)
        self.PackageTitile.setObjectName("PackageTitile")
        self.verticalLayout.addWidget(self.PackageTitile)
        self.container = QtWidgets.QWidget(Dubbing)
        self.container.setObjectName("container")
        self.gridLayout = QtWidgets.QGridLayout(self.container)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.containerLayout = QtWidgets.QGridLayout()
        self.containerLayout.setContentsMargins(0, 0, 0, 0)
        self.containerLayout.setSpacing(0)
        self.containerLayout.setObjectName("containerLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.container)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 951, 805))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setContentsMargins(0, 2, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_container = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_container.setStyleSheet("#frame_7{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_container.setObjectName("frame_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_container)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_1 = QtWidgets.QFrame(self.frame_container)
        self.frame_1.setStyleSheet("#frame_1{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tool1_title = QtWidgets.QLabel(self.frame_1)
        self.tool1_title.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool1_title.setFont(font)
        self.tool1_title.setObjectName("tool1_title")
        self.verticalLayout_2.addWidget(self.tool1_title)
        self.videoBox = QtWidgets.QFrame(self.frame_1)
        self.videoBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videoBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoBox.setObjectName("videoBox")
        self.verticalLayout_2.addWidget(self.videoBox)
        self.verticalLayout_2.setStretch(1, 4)
        self.horizontalLayout_2.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(self.frame_container)
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tool2_title = QtWidgets.QLabel(self.frame_2)
        self.tool2_title.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool2_title.setFont(font)
        self.tool2_title.setObjectName("tool2_title")
        self.verticalLayout_3.addWidget(self.tool2_title)
        self.subtitleBox = QtWidgets.QFrame(self.frame_2)
        self.subtitleBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subtitleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subtitleBox.setObjectName("subtitleBox")
        self.verticalLayout_3.addWidget(self.subtitleBox)
        self.verticalLayout_3.setStretch(1, 4)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_container)
        self.info_container = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.info_container.setStyleSheet("#frame_7{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.info_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_container.setObjectName("info_container")
        self.verticalLayout_4.addWidget(self.info_container)
        self.operate_container = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.operate_container.setStyleSheet("#frame_7{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.operate_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.operate_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.operate_container.setObjectName("operate_container")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.operate_container)
        self.verticalLayout_5.setContentsMargins(0, 0, -1, 2)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.extraOutputBtn = RadioButton(self.operate_container)
        self.extraOutputBtn.setObjectName("extraOutputBtn")
        self.verticalLayout_5.addWidget(self.extraOutputBtn)
        self.separateBtn = PushButton(self.operate_container)
        self.separateBtn.setObjectName("separateBtn")
        self.verticalLayout_5.addWidget(self.separateBtn)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dubbingBtn = PushButton(self.operate_container)
        self.dubbingBtn.setObjectName("dubbingBtn")
        self.horizontalLayout_3.addWidget(self.dubbingBtn)
        self.editBtn = PushButton(self.operate_container)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout_3.addWidget(self.editBtn)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.operate_container)
        self.verticalLayout_4.setStretch(0, 4)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.containerLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.roleFrame = QtWidgets.QFrame(self.container)
        self.roleFrame.setObjectName("roleFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.roleFrame)
        self.verticalLayout_6.setContentsMargins(2, -1, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DelVoiceBtn = PushButton(self.roleFrame)
        self.DelVoiceBtn.setObjectName("DelVoiceBtn")
        self.horizontalLayout.addWidget(self.DelVoiceBtn)
        self.PullVoiceBtn = PushButton(self.roleFrame)
        self.PullVoiceBtn.setObjectName("PullVoiceBtn")
        self.horizontalLayout.addWidget(self.PullVoiceBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.tool1_title_2 = QtWidgets.QLabel(self.roleFrame)
        self.tool1_title_2.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool1_title_2.setFont(font)
        self.tool1_title_2.setObjectName("tool1_title_2")
        self.verticalLayout_6.addWidget(self.tool1_title_2)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.roleFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.roleScrollArea = QtWidgets.QWidget()
        self.roleScrollArea.setGeometry(QtCore.QRect(0, 0, 313, 732))
        self.roleScrollArea.setObjectName("roleScrollArea")
        self.scrollArea_2.setWidget(self.roleScrollArea)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.containerLayout.addWidget(self.roleFrame, 0, 1, 1, 1)
        self.containerLayout.setColumnStretch(0, 3)
        self.containerLayout.setColumnStretch(1, 1)
        self.gridLayout.addLayout(self.containerLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.container)

        self.retranslateUi(Dubbing)
        QtCore.QMetaObject.connectSlotsByName(Dubbing)

    def retranslateUi(self, Dubbing):
        _translate = QtCore.QCoreApplication.translate
        Dubbing.setWindowTitle(_translate("Dubbing", "Form"))
        self.PackageTitile.setText(_translate("Dubbing", "批量配音"))
        self.tool1_title.setText(_translate("Dubbing", "视频文件"))
        self.tool2_title.setText(_translate("Dubbing", "已标注的字幕文件"))
        self.extraOutputBtn.setText(_translate("Dubbing", "是否导出角色干音"))
        self.separateBtn.setText(_translate("Dubbing", "开始批量提取干音"))
        self.dubbingBtn.setText(_translate("Dubbing", "开始批量配音"))
        self.editBtn.setText(_translate("Dubbing", "配音编辑器"))
        self.DelVoiceBtn.setText(_translate("Dubbing", "管理声音"))
        self.PullVoiceBtn.setText(_translate("Dubbing", "同步声音列表"))
        self.tool1_title_2.setText(_translate("Dubbing", "角色声音选择器"))
from qfluentwidgets import PushButton, RadioButton
