# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_subtitleEdit.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SubtitleEdit(object):
    def setupUi(self, SubtitleEdit):
        SubtitleEdit.setObjectName("SubtitleEdit")
        SubtitleEdit.resize(1468, 817)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SubtitleEdit)
        self.verticalLayout_2.setContentsMargins(12, 32, 16, 16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PackageTitile = QtWidgets.QLabel(SubtitleEdit)
        self.PackageTitile.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.PackageTitile.setFont(font)
        self.PackageTitile.setObjectName("PackageTitile")
        self.verticalLayout_2.addWidget(self.PackageTitile)
        self.Tools = QtWidgets.QVBoxLayout()
        self.Tools.setSpacing(0)
        self.Tools.setObjectName("Tools")
        self.M3U8Box = SimpleCardWidget(SubtitleEdit)
        self.M3U8Box.setMinimumSize(QtCore.QSize(0, 42))
        self.M3U8Box.setObjectName("M3U8Box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.M3U8Box)
        self.horizontalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.M3U8Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.M3U8Box)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.DubbingSelector = QtWidgets.QComboBox(self.M3U8Box)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.DubbingSelector.setFont(font)
        self.DubbingSelector.setObjectName("DubbingSelector")
        self.horizontalLayout_3.addWidget(self.DubbingSelector)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.ElevenDubbingBtn = PushButton(self.M3U8Box)
        self.ElevenDubbingBtn.setObjectName("ElevenDubbingBtn")
        self.horizontalLayout_3.addWidget(self.ElevenDubbingBtn)
        self.DelVoiceBtn = PushButton(self.M3U8Box)
        self.DelVoiceBtn.setObjectName("DelVoiceBtn")
        self.horizontalLayout_3.addWidget(self.DelVoiceBtn)
        self.PullVoiceBtn = PushButton(self.M3U8Box)
        self.PullVoiceBtn.setObjectName("PullVoiceBtn")
        self.horizontalLayout_3.addWidget(self.PullVoiceBtn)
        self.Tools.addWidget(self.M3U8Box)
        self.verticalLayout_2.addLayout(self.Tools)
        self.widget = QtWidgets.QWidget(SubtitleEdit)
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SubUpload = QtWidgets.QVBoxLayout()
        self.SubUpload.setObjectName("SubUpload")
        self.MP4Title = QtWidgets.QLabel(self.widget)
        self.MP4Title.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.MP4Title.setFont(font)
        self.MP4Title.setObjectName("MP4Title")
        self.SubUpload.addWidget(self.MP4Title)
        self.btnbox = QtWidgets.QHBoxLayout()
        self.btnbox.setObjectName("btnbox")
        self.AddSubBtn = PushButton(self.widget)
        self.AddSubBtn.setObjectName("AddSubBtn")
        self.btnbox.addWidget(self.AddSubBtn)
        self.SubUpload.addLayout(self.btnbox)
        self.SubListBox = QtWidgets.QWidget(self.widget)
        self.SubListBox.setMinimumSize(QtCore.QSize(0, 430))
        self.SubListBox.setStyleSheet("#SubListBox{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.SubListBox.setObjectName("SubListBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.SubListBox)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SubListWidget = ListWidget(self.SubListBox)
        self.SubListWidget.setObjectName("SubListWidget")
        self.gridLayout_4.addWidget(self.SubListWidget, 0, 0, 1, 1)
        self.SubListDropHint = QtWidgets.QLabel(self.SubListBox)
        self.SubListDropHint.setStyleSheet("#SubListDropHint{\n"
"color: rgba(0,0,0,140);\n"
"font: 14pt \"Microsoft YaHei UI\";\n"
"background: transparent;\n"
"}")
        self.SubListDropHint.setAlignment(QtCore.Qt.AlignCenter)
        self.SubListDropHint.setObjectName("SubListDropHint")
        self.gridLayout_4.addWidget(self.SubListDropHint, 0, 0, 1, 1)
        self.SubUpload.addWidget(self.SubListBox)
        self.SubUpload.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.SubUpload)
        self.Mkv = QtWidgets.QVBoxLayout()
        self.Mkv.setContentsMargins(-1, -1, -1, 0)
        self.Mkv.setSpacing(6)
        self.Mkv.setObjectName("Mkv")
        self.MkvTitle = QtWidgets.QLabel(self.widget)
        self.MkvTitle.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.MkvTitle.setFont(font)
        self.MkvTitle.setObjectName("MkvTitle")
        self.Mkv.addWidget(self.MkvTitle)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddVideoBtn = PushButton(self.widget)
        self.AddVideoBtn.setObjectName("AddVideoBtn")
        self.horizontalLayout.addWidget(self.AddVideoBtn)
        self.AIDubbingBtn = PushButton(self.widget)
        self.AIDubbingBtn.setObjectName("AIDubbingBtn")
        self.horizontalLayout.addWidget(self.AIDubbingBtn)
        self.AIDirectedBtn = PushButton(self.widget)
        self.AIDirectedBtn.setObjectName("AIDirectedBtn")
        self.horizontalLayout.addWidget(self.AIDirectedBtn)
        self.AIVoiceBtn = PushButton(self.widget)
        self.AIVoiceBtn.setObjectName("AIVoiceBtn")
        self.horizontalLayout.addWidget(self.AIVoiceBtn)
        self.CosyDubbingBtn = PushButton(self.widget)
        self.CosyDubbingBtn.setObjectName("CosyDubbingBtn")
        self.horizontalLayout.addWidget(self.CosyDubbingBtn)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 3)
        self.Mkv.addLayout(self.horizontalLayout)
        self.CustomVideoWidget = QtWidgets.QWidget(self.widget)
        self.CustomVideoWidget.setStyleSheet("#CustomVideoWidget{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.CustomVideoWidget.setObjectName("CustomVideoWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CustomVideoWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.VideoDropHint = QtWidgets.QLabel(self.CustomVideoWidget)
        self.VideoDropHint.setStyleSheet("#VideoDropHint{\n"
"color: rgba(0,0,0,140);\n"
"font: 14pt \"Microsoft YaHei UI\";\n"
"background: transparent;\n"
"}")
        self.VideoDropHint.setAlignment(QtCore.Qt.AlignCenter)
        self.VideoDropHint.setObjectName("VideoDropHint")
        self.verticalLayout.addWidget(self.VideoDropHint)
        self.Mkv.addWidget(self.CustomVideoWidget)
        self.Mkv.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.Mkv)
        self.SubList = QtWidgets.QVBoxLayout()
        self.SubList.setObjectName("SubList")
        self.MP4Title_2 = QtWidgets.QLabel(self.widget)
        self.MP4Title_2.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.MP4Title_2.setFont(font)
        self.MP4Title_2.setObjectName("MP4Title_2")
        self.SubList.addWidget(self.MP4Title_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.AutoMarkBtn = PushButton(self.widget)
        self.AutoMarkBtn.setObjectName("AutoMarkBtn")
        self.horizontalLayout_4.addWidget(self.AutoMarkBtn)
        self.SaveBtn = PushButton(self.widget)
        self.SaveBtn.setObjectName("SaveBtn")
        self.horizontalLayout_4.addWidget(self.SaveBtn)
        self.ExportBtn = PushButton(self.widget)
        self.ExportBtn.setObjectName("ExportBtn")
        self.horizontalLayout_4.addWidget(self.ExportBtn)
        self.ImportRoleBtn = PushButton(self.widget)
        self.ImportRoleBtn.setObjectName("ImportRoleBtn")
        self.horizontalLayout_4.addWidget(self.ImportRoleBtn)
        self.OutputRoleBtn = PushButton(self.widget)
        self.OutputRoleBtn.setObjectName("OutputRoleBtn")
        self.horizontalLayout_4.addWidget(self.OutputRoleBtn)
        self.SubList.addLayout(self.horizontalLayout_4)
        self.MP4Box_2 = QtWidgets.QWidget(self.widget)
        self.MP4Box_2.setMinimumSize(QtCore.QSize(0, 430))
        self.MP4Box_2.setObjectName("MP4Box_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.MP4Box_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.SubScroll = QtWidgets.QScrollArea(self.MP4Box_2)
        self.SubScroll.setWidgetResizable(True)
        self.SubScroll.setObjectName("SubScroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 525))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SubScroll.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.SubScroll, 0, 0, 1, 1)
        self.SubList.addWidget(self.MP4Box_2)
        self.SubList.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.SubList)
        self.RoleList = QtWidgets.QVBoxLayout()
        self.RoleList.setObjectName("RoleList")
        self.MP4Title_3 = QtWidgets.QLabel(self.widget)
        self.MP4Title_3.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.MP4Title_3.setFont(font)
        self.MP4Title_3.setObjectName("MP4Title_3")
        self.RoleList.addWidget(self.MP4Title_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AddRoleBtn = PushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddRoleBtn.sizePolicy().hasHeightForWidth())
        self.AddRoleBtn.setSizePolicy(sizePolicy)
        self.AddRoleBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.AddRoleBtn.setObjectName("AddRoleBtn")
        self.horizontalLayout_2.addWidget(self.AddRoleBtn)
        self.RoleList.addLayout(self.horizontalLayout_2)
        self.RoleListBox = QtWidgets.QWidget(self.widget)
        self.RoleListBox.setStyleSheet("#RoleListBox{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.RoleListBox.setObjectName("RoleListBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.RoleListBox)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RoleListWidget = ListWidget(self.RoleListBox)
        self.RoleListWidget.setObjectName("RoleListWidget")
        self.gridLayout_2.addWidget(self.RoleListWidget, 0, 0, 1, 1)
        self.RoleList.addWidget(self.RoleListBox)
        self.RoleList.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.RoleList)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_5.setStretch(2, 2)
        self.horizontalLayout_5.setStretch(3, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.BottomBar = QtWidgets.QWidget(SubtitleEdit)
        self.BottomBar.setMinimumSize(QtCore.QSize(0, 46))
        self.BottomBar.setMaximumSize(QtCore.QSize(16777215, 46))
        self.BottomBar.setStyleSheet("#BottomBar{\n"
"border-top: 1px solid #e5e5e5;\n"
"}")
        self.BottomBar.setObjectName("BottomBar")
        self.bottomBarLayout = QtWidgets.QHBoxLayout(self.BottomBar)
        self.bottomBarLayout.setContentsMargins(0, 0, 0, 0)
        self.bottomBarLayout.setObjectName("bottomBarLayout")
        self.BottomPlayBtn = PushButton(self.BottomBar)
        self.BottomPlayBtn.setObjectName("BottomPlayBtn")
        self.bottomBarLayout.addWidget(self.BottomPlayBtn)
        self.BottomTimeLabel = BodyLabel(self.BottomBar)
        self.BottomTimeLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.BottomTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.BottomTimeLabel.setObjectName("BottomTimeLabel")
        self.bottomBarLayout.addWidget(self.BottomTimeLabel)
        self.BottomPositionSlider = Slider(self.BottomBar)
        self.BottomPositionSlider.setMinimum(0)
        self.BottomPositionSlider.setMaximum(0)
        self.BottomPositionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BottomPositionSlider.setObjectName("BottomPositionSlider")
        self.bottomBarLayout.addWidget(self.BottomPositionSlider)
        self.bottomBarLayout.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.BottomBar)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 20)

        self.retranslateUi(SubtitleEdit)
        QtCore.QMetaObject.connectSlotsByName(SubtitleEdit)

    def retranslateUi(self, SubtitleEdit):
        _translate = QtCore.QCoreApplication.translate
        SubtitleEdit.setWindowTitle(_translate("SubtitleEdit", "Form"))
        self.PackageTitile.setText(_translate("SubtitleEdit", "字幕编辑器"))
        self.label.setText(_translate("SubtitleEdit", "配音AI"))
        self.ElevenDubbingBtn.setText(_translate("SubtitleEdit", "Elevenlabs配音"))
        self.DelVoiceBtn.setText(_translate("SubtitleEdit", "管理声音"))
        self.PullVoiceBtn.setText(_translate("SubtitleEdit", "同步声音列表"))
        self.MP4Title.setText(_translate("SubtitleEdit", "字幕文件列表"))
        self.AddSubBtn.setText(_translate("SubtitleEdit", "上传字幕"))
        self.SubListDropHint.setText(_translate("SubtitleEdit", "拖拽上传字幕"))
        self.MkvTitle.setText(_translate("SubtitleEdit", "视频"))
        self.AddVideoBtn.setText(_translate("SubtitleEdit", "上传视频"))
        self.AIDubbingBtn.setText(_translate("SubtitleEdit", "AI自动配音"))
        self.AIDirectedBtn.setText(_translate("SubtitleEdit", "AI无原音配音"))
        self.AIVoiceBtn.setText(_translate("SubtitleEdit", "AI声线转换"))
        self.CosyDubbingBtn.setText(_translate("SubtitleEdit", "CosyVoice配音"))
        self.VideoDropHint.setText(_translate("SubtitleEdit", "拖拽上传视频"))
        self.MP4Title_2.setText(_translate("SubtitleEdit", "字幕列表"))
        self.AutoMarkBtn.setText(_translate("SubtitleEdit", "AI标注"))
        self.SaveBtn.setText(_translate("SubtitleEdit", "保存"))
        self.ExportBtn.setText(_translate("SubtitleEdit", "导出"))
        self.ImportRoleBtn.setText(_translate("SubtitleEdit", "导入角色表"))
        self.OutputRoleBtn.setText(_translate("SubtitleEdit", "导出角色表"))
        self.MP4Title_3.setText(_translate("SubtitleEdit", "角色列表"))
        self.AddRoleBtn.setText(_translate("SubtitleEdit", "新增角色"))
        self.BottomPlayBtn.setText(_translate("SubtitleEdit", "播放"))
        self.BottomTimeLabel.setText(_translate("SubtitleEdit", "00:00:00,000"))
from qfluentwidgets import BodyLabel, ListWidget, PushButton, SimpleCardWidget, Slider
