# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_tools.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tools(object):
    def setupUi(self, Tools):
        Tools.setObjectName("Tools")
        Tools.resize(1300, 910)
        self.verticalLayout = QtWidgets.QVBoxLayout(Tools)
        self.verticalLayout.setContentsMargins(12, 32, 16, 16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PackageTitile = QtWidgets.QLabel(Tools)
        self.PackageTitile.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.PackageTitile.setFont(font)
        self.PackageTitile.setObjectName("PackageTitile")
        self.verticalLayout.addWidget(self.PackageTitile)
        self.container = QtWidgets.QWidget(Tools)
        self.container.setObjectName("container")
        self.gridLayout = QtWidgets.QGridLayout(self.container)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.containerLayout = QtWidgets.QGridLayout()
        self.containerLayout.setContentsMargins(0, 0, 0, 0)
        self.containerLayout.setSpacing(0)
        self.containerLayout.setObjectName("containerLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.container)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 200))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1268, 805))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_1 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_1.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_1.setStyleSheet("#frame_1{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tool1_title = QtWidgets.QLabel(self.frame_1)
        self.tool1_title.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool1_title.setFont(font)
        self.tool1_title.setObjectName("tool1_title")
        self.gridLayout_3.addWidget(self.tool1_title, 0, 0, 1, 1)
        self.compressBtn = PushButton(self.frame_1)
        self.compressBtn.setObjectName("compressBtn")
        self.gridLayout_3.addWidget(self.compressBtn, 0, 2, 1, 1)
        self.compressBox = QtWidgets.QFrame(self.frame_1)
        self.compressBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.compressBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.compressBox.setObjectName("compressBox")
        self.gridLayout_3.addWidget(self.compressBox, 1, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(173, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.gridLayout_2.addWidget(self.frame_1, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tool2_title = QtWidgets.QLabel(self.frame_2)
        self.tool2_title.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool2_title.setFont(font)
        self.tool2_title.setObjectName("tool2_title")
        self.gridLayout_4.addWidget(self.tool2_title, 0, 0, 1, 1)
        self.mergeVideoBtn = PushButton(self.frame_2)
        self.mergeVideoBtn.setObjectName("mergeVideoBtn")
        self.gridLayout_4.addWidget(self.mergeVideoBtn, 0, 2, 1, 1)
        self.mergeVideoBox = QtWidgets.QFrame(self.frame_2)
        self.mergeVideoBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mergeVideoBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mergeVideoBox.setObjectName("mergeVideoBox")
        self.gridLayout_4.addWidget(self.mergeVideoBox, 1, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(193, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setColumnStretch(2, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mergeSubtitleVideoBox = QtWidgets.QFrame(self.frame_3)
        self.mergeSubtitleVideoBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mergeSubtitleVideoBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mergeSubtitleVideoBox.setObjectName("mergeSubtitleVideoBox")
        self.gridLayout_5.addWidget(self.mergeSubtitleVideoBox, 1, 2, 1, 2)
        self.tool3_title = QtWidgets.QLabel(self.frame_3)
        self.tool3_title.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool3_title.setFont(font)
        self.tool3_title.setObjectName("tool3_title")
        self.gridLayout_5.addWidget(self.tool3_title, 0, 0, 1, 1)
        self.splitSubtitleBtn = PushButton(self.frame_3)
        self.splitSubtitleBtn.setObjectName("splitSubtitleBtn")
        self.gridLayout_5.addWidget(self.splitSubtitleBtn, 0, 3, 1, 1)
        self.mergeSubtitleBox = QtWidgets.QFrame(self.frame_3)
        self.mergeSubtitleBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mergeSubtitleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mergeSubtitleBox.setObjectName("mergeSubtitleBox")
        self.gridLayout_5.addWidget(self.mergeSubtitleBox, 1, 0, 1, 2)
        self.mergeSubtitleBtn = PushButton(self.frame_3)
        self.mergeSubtitleBtn.setObjectName("mergeSubtitleBtn")
        self.gridLayout_5.addWidget(self.mergeSubtitleBtn, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(197, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout_5.setColumnStretch(3, 1)
        self.gridLayout_2.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet("#frame_4{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tool4_title = QtWidgets.QLabel(self.frame_4)
        self.tool4_title.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool4_title.setFont(font)
        self.tool4_title.setObjectName("tool4_title")
        self.gridLayout_6.addWidget(self.tool4_title, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(196, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 1, 1, 1)
        self.cloneVoiceBtn = PushButton(self.frame_4)
        self.cloneVoiceBtn.setObjectName("cloneVoiceBtn")
        self.gridLayout_6.addWidget(self.cloneVoiceBtn, 0, 2, 1, 1)
        self.cloneVoiceBox = QtWidgets.QFrame(self.frame_4)
        self.cloneVoiceBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cloneVoiceBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cloneVoiceBox.setObjectName("cloneVoiceBox")
        self.gridLayout_6.addWidget(self.cloneVoiceBox, 1, 0, 1, 3)
        self.gridLayout_2.addWidget(self.frame_4, 1, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setStyleSheet("#frame_5{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tool3_title_2 = QtWidgets.QLabel(self.frame_5)
        self.tool3_title_2.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool3_title_2.setFont(font)
        self.tool3_title_2.setObjectName("tool3_title_2")
        self.gridLayout_7.addWidget(self.tool3_title_2, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 0, 2, 1, 1)
        self.syncSubtitleBtn = PushButton(self.frame_5)
        self.syncSubtitleBtn.setObjectName("syncSubtitleBtn")
        self.gridLayout_7.addWidget(self.syncSubtitleBtn, 0, 3, 1, 1)
        self.srcSubtitleBox = QtWidgets.QFrame(self.frame_5)
        self.srcSubtitleBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.srcSubtitleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.srcSubtitleBox.setObjectName("srcSubtitleBox")
        self.gridLayout_7.addWidget(self.srcSubtitleBox, 1, 0, 1, 2)
        self.dstSubtitleBox = QtWidgets.QFrame(self.frame_5)
        self.dstSubtitleBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dstSubtitleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dstSubtitleBox.setObjectName("dstSubtitleBox")
        self.gridLayout_7.addWidget(self.dstSubtitleBox, 1, 2, 1, 2)
        self.gridLayout_7.setRowMinimumHeight(1, 1)
        self.gridLayout_7.setColumnStretch(0, 1)
        self.gridLayout_7.setColumnStretch(1, 1)
        self.gridLayout_7.setColumnStretch(2, 1)
        self.gridLayout_7.setColumnStretch(3, 1)
        self.gridLayout_2.addWidget(self.frame_5, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setStyleSheet("#frame_6{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tool4_title_2 = QtWidgets.QLabel(self.frame_6)
        self.tool4_title_2.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool4_title_2.setFont(font)
        self.tool4_title_2.setObjectName("tool4_title_2")
        self.gridLayout_8.addWidget(self.tool4_title_2, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(196, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 0, 1, 1, 1)
        self.clearbgmBtn = PushButton(self.frame_6)
        self.clearbgmBtn.setObjectName("clearbgmBtn")
        self.gridLayout_8.addWidget(self.clearbgmBtn, 0, 2, 1, 1)
        self.clearbgmBox = QtWidgets.QFrame(self.frame_6)
        self.clearbgmBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clearbgmBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clearbgmBox.setObjectName("clearbgmBox")
        self.gridLayout_8.addWidget(self.clearbgmBox, 1, 0, 1, 3)
        self.gridLayout_2.addWidget(self.frame_6, 2, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_7.setStyleSheet("#frame_7{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tool3_title_3 = QtWidgets.QLabel(self.frame_7)
        self.tool3_title_3.setMaximumSize(QtCore.QSize(16777215, 3000))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tool3_title_3.setFont(font)
        self.tool3_title_3.setObjectName("tool3_title_3")
        self.gridLayout_9.addWidget(self.tool3_title_3, 0, 0, 1, 1)
        self.splitVideoBtn = PushButton(self.frame_7)
        self.splitVideoBtn.setObjectName("splitVideoBtn")
        self.gridLayout_9.addWidget(self.splitVideoBtn, 0, 3, 1, 1)
        self.srcVideoBox = QtWidgets.QFrame(self.frame_7)
        self.srcVideoBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.srcVideoBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.srcVideoBox.setObjectName("srcVideoBox")
        self.gridLayout_9.addWidget(self.srcVideoBox, 1, 0, 1, 2)
        self.dstVideoBox = QtWidgets.QFrame(self.frame_7)
        self.dstVideoBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dstVideoBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dstVideoBox.setObjectName("dstVideoBox")
        self.gridLayout_9.addWidget(self.dstVideoBox, 1, 2, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(143, 24, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(143, 24, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem8, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_7, 3, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_8.setStyleSheet("#frame_8{\n"
"    border: 1px solid #ccc;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_2.addWidget(self.frame_8, 3, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.containerLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.containerLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.container)

        self.retranslateUi(Tools)
        QtCore.QMetaObject.connectSlotsByName(Tools)

    def retranslateUi(self, Tools):
        _translate = QtCore.QCoreApplication.translate
        Tools.setWindowTitle(_translate("Tools", "Form"))
        self.PackageTitile.setText(_translate("Tools", "工具箱"))
        self.tool1_title.setText(_translate("Tools", "压缩视频大小（1080p）"))
        self.compressBtn.setText(_translate("Tools", "开始任务"))
        self.tool2_title.setText(_translate("Tools", "合并视频文件"))
        self.mergeVideoBtn.setText(_translate("Tools", "开始任务"))
        self.tool3_title.setText(_translate("Tools", "合并字幕文件"))
        self.splitSubtitleBtn.setText(_translate("Tools", "拆分字幕"))
        self.mergeSubtitleBtn.setText(_translate("Tools", "合并字幕"))
        self.tool4_title.setText(_translate("Tools", "克隆声音"))
        self.cloneVoiceBtn.setText(_translate("Tools", "开始克隆"))
        self.tool3_title_2.setText(_translate("Tools", "同步字幕角色"))
        self.syncSubtitleBtn.setText(_translate("Tools", "同步角色列表"))
        self.tool4_title_2.setText(_translate("Tools", "去除视频背景声"))
        self.clearbgmBtn.setText(_translate("Tools", "开始任务"))
        self.tool3_title_3.setText(_translate("Tools", "拆分视频文件"))
        self.splitVideoBtn.setText(_translate("Tools", "拆分视频"))
from qfluentwidgets import PushButton
